

plugins {
   id 'java'
    id 'application'

   // id 'org.openjfx.javafxplugin' version '0.0.14'

    id 'com.github.johnrengelman.shadow' version '7.1.2'
}

shadowJar {
    archiveBaseName.set('moraysalgovisualizer')
    archiveClassifier.set('')
    archiveVersion.set('')
    mergeServiceFiles()
    manifest {
        attributes 'Main-Class': 'runner.Servermain'
    }
}

repositories {
    mavenCentral()
}
tasks.startShadowScripts.enabled = false
tasks.shadowDistZip.enabled = false
tasks.shadowDistTar.enabled = false
tasks.distZip.enabled = false
tasks.distTar.enabled = false
tasks.startScripts.enabled = false

application {
    mainClass = 'runner.Servermain'
}


tasks.jar {
    manifest {
        attributes(
                'Main-Class': application.mainClass.get()
        )
    }
}


sourceSets {
    main {
        java {
            exclude 'runner/Main.java'
            exclude 'animations/**'
            exclude 'runner/User_safe_interface_api.java'
        }
    }
}


// Configure Java compilation to use the toolchain
java {
  //  toolchain {
 //       languageVersion = JavaLanguageVersion.of(24)
  //  }
}



//javafx {version = "25"modules = [ 'javafx.controls', 'javafx.fxml', 'javafx.graphics' ]}

dependencies {
    implementation "org.graalvm.sdk:graal-sdk:24.2.2"
   // implementation "org.graalvm.truffle:truffle-api:24.2.2"
  //  implementation "org.graalvm.js:js-engine:24.2.2"

   // implementation "org.graalvm.js:js:24.2.2"
    //implementation "org.graalvm.js:js-scriptengine:24.2.2"


    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

}



test {
    useJUnitPlatform()

    // Skip GUI tests in CI environment
    if (System.getenv('CI') != null) {
        exclude '**/Visual_partTest*'
        exclude '**/User_safe_interface_apiTest*'
        exclude '**/AlgorithmRunnerTest*'
    }


}




