name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Java 24 Manually
      run: |
        wget -q https://github.com/adoptium/temurin24-binaries/releases/download/jdk-24.0.1%2B12/OpenJDK24U-jdk_x64_linux_hotspot_24.0.1_12.tar.gz
        sudo mkdir -p /usr/lib/jvm
        sudo tar -xzf OpenJDK24U-jdk_x64_linux_hotspot_24.0.1_12.tar.gz -C /usr/lib/jvm
        echo "JAVA_HOME=/usr/lib/jvm/jdk-24.0.1+12" >> $GITHUB_ENV
        echo "/usr/lib/jvm/jdk-24.0.1+12/bin" >> $GITHUB_PATH
    
    - name: Verify Java
      run: java -version
    
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    
    - name: Build with Gradle
      run: ./gradlew build
