name: Build

on:
  push:
    branches: [ master, shifting_awayfrom_javafx ]
  pull_request:
    branches: [ master, shifting_awayfrom_javafx ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '21'
          components: 'js'

      - name: Verify Java
        run: java -version

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

     # - name: Build with Gradle
      #  run: ./gradlew shadowJar --no-daemon -x test